apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: demo-repo
spec:
  type: git
  params:
    - name: revision
      value: feat/tekton
    - name: url
      value: https://github.com/romdhanisam/lab-tekton